spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog427?useSSL=false&serverTimezone=UTC
    username: root
    password: 88888888
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapperLocations: classpath:ncg/mapper/*.xml
server:
  port: 8081